name: 'Database DevOps'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      env:
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        SQL_SERVER_NAME: ${{ secrets.SQL_SERVER_NAME }}
        SQL_DATABASE_NAME: ${{ secrets.SQL_DATABASE_NAME }}
        ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
      run: |
        terraform apply -auto-approve \
          -var="admin_password=${ADMIN_PASSWORD}" \
          -var="subscription_id=${SUBSCRIPTION_ID}" \
          -var="sql_server_name=${SQL_SERVER_NAME}" \
          -var="sql_database_name=${SQL_DATABASE_NAME}" \
          -var="admin_username=${ADMIN_USERNAME}"