name: "Create Infrastructure"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  IAC:
    runs-on: ubuntu-latest
    env:
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      SQL_SERVER_NAME: ${{ secrets.SQL_SERVER_NAME }}
      SQL_DATABASE_NAME: ${{ secrets.SQL_DATABASE_NAME }}
      ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
      BACKEND_RESOURCE_GROUP_NAME: ${{ secrets.BACKEND_RESOURCE_GROUP_NAME }}
      BACKEND_STORAGE_ACCOUNT_NAME: ${{ secrets.BACKEND_STORAGE_ACCOUNT_NAME }}
      BACKEND_CONTAINER_NAME: ${{ secrets.BACKEND_CONTAINER_NAME }}
      BACKEND_KEY: ${{ secrets.BACKEND_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init -backend-config="resource_group_name=${BACKEND_RESOURCE_GROUP_NAME}" -backend-config="storage_account_name=${BACKEND_STORAGE_ACCOUNT_NAME}" -backend-config="container_name=${BACKEND_CONTAINER_NAME}" -backend-config="key=${BACKEND_KEY}"

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="admin_password=${ADMIN_PASSWORD}" \
            -var="subscription_id=${SUBSCRIPTION_ID}" \
            -var="sql_server_name=${SQL_SERVER_NAME}" \
            -var="sql_database_name=${SQL_DATABASE_NAME}" \
            -var="admin_username=${ADMIN_USERNAME}"

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          terraform apply -auto-approve \
            -var="admin_password=${ADMIN_PASSWORD}" \
            -var="subscription_id=${SUBSCRIPTION_ID}" \
            -var="sql_server_name=${SQL_SERVER_NAME}" \
            -var="sql_database_name=${SQL_DATABASE_NAME}" \
            -var="admin_username=${ADMIN_USERNAME}"
