name: "Destroy Infrastructure"

on:
  workflow_dispatch:

jobs:
  IAC_Destroy:
    runs-on: ubuntu-latest
    env:
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      SQL_SERVER_NAME: ${{ secrets.SQL_SERVER_NAME }}
      SQL_DATABASE_NAME: ${{ secrets.SQL_DATABASE_NAME }}
      ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve \
            -var="admin_password=${ADMIN_PASSWORD}" \
            -var="subscription_id=${SUBSCRIPTION_ID}" \
            -var="sql_server_name=${SQL_SERVER_NAME}" \
            -var="sql_database_name=${SQL_DATABASE_NAME}" \
            -var="admin_username=${ADMIN_USERNAME}"
