name: Liquibase Update

on:
  push:
    branches:
      - dev

jobs:
  liquibase-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Liquibase Migrations for DEV
        if: github.ref == 'refs/heads/dev'
        uses: liquibase-github-actions/update@v4.28.0
        with:
          url: "jdbc:sqlserver://${{ secrets.SQL_SERVER_NAME }}.database.windows.net:1433;databaseName=${{ secrets.SQL_DATABASE_NAME }}-dev;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;"
          username: ${{ secrets.ADMIN_USERNAME }}
          password: ${{ secrets.ADMIN_PASSWORD }}
          changelogFile: "liquibase/changelog.json"
          driver: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
          showSummaryOutput: "log"
          contextFilter: "dev"

      - name: Run Liquibase Update for main
        if: github.ref == 'refs/heads/main'
        uses: liquibase-github-actions/update@v4.28.0
        with:
          url: "jdbc:sqlserver://${{ secrets.SQL_SERVER_NAME }}.database.windows.net:1433;databaseName=${{ secrets.SQL_DATABASE_NAME }}-prod;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;"
          username: ${{ secrets.ADMIN_USERNAME }}
          password: ${{ secrets.ADMIN_PASSWORD }}
          changelogFile: "liquibase/changelog.json"
          driver: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
          showSummaryOutput: "log"
          contextFilter: "prod"
